## 🧮 Calculative Foundation

### 📚 Importing Libraries

In [1]:
# Numerical Computation
import numpy as np

# Data Handling
import pandas as pd

# Plotting
import matplotlib.pyplot as plt

# Linear Algebra
from numpy.linalg import norm, inv, det, eig

# LU Decomposition
from scipy.linalg import lu

# PCA & LDA
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")

### 📂 Loaded Dataset

In [2]:
df = pd.read_excel("student_performance_dataset.xlsx")
print("Read the successfully")

Read the successfully

###  👀 Display First 5 Rows

In [3]:

df.head()

,Student_ID,Name,Math,Physics,Chemistry,English,Computer,Attendance,Final_Result
0,S001,Aarav,88,82,85,78,91,94,Above Average
1,S002,Diya,72,69,74,81,76,90,Below Average
2,S003,Vivaan,95,91,89,86,97,98,Above Average
3,S004,Anaya,61,65,63,70,68,84,Below Average
4,S005,Aditya,79,83,81,75,88,93,Above Average

#### ℹ️ Dataset Information

In [4]:
# Shape
print("Shape :", df.shape)

Shape : (20, 9)

In [5]:
# Column Names
print(df.columns)

Index(['Student_ID', 'Name', 'Math', 'Physics', 'Chemistry', 'English',
       'Computer', 'Attendance', 'Final_Result'],
      dtype='str')

In [6]:
# Dataset Information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    20 non-null     str
 1   Name          20 non-null     str
 2   Math          20 non-null     int64
 3   Physics       20 non-null     int64
 4   Chemistry     20 non-null     int64
 5   English       20 non-null     int64
 6   Computer      20 non-null     int64
 7   Attendance    20 non-null     int64
 8   Final_Result  20 non-null     str
dtypes: int64(6), str(3)
memory usage: 1.5 KB

### ❓ Check Missing Values

In [7]:
df.isnull().sum()

Student_ID      0
Name            0
Math            0
Physics         0
Chemistry       0
English         0
Computer        0
Attendance      0
Final_Result    0
dtype: int64

### 🔢 Select Only Numerical Columns

In [8]:
subjects = ["Math","Physics","Chemistry","English","Computer"]

data = df[subjects]

data.head()

   Math  Physics  Chemistry  English  Computer
0    88       82         85       78        91
1    72       69         74       81        76
2    95       91         89       86        97
3    61       65         63       70        68
4    79       83         81       75        88

### 🧩 Convert Dataset into Matrix

In [9]:
matrix = data.values

print(matrix)

[[88 82 85 78 91]
 [72 69 74 81 76]
 [95 91 89 86 97]
 [61 65 63 70 68]
 [79 83 81 75 88]
 [68 71 69 74 72]
 [92 94 90 88 95]
 [75 78 73 80 77]
 [84 86 82 79 90]
 [66 64 67 72 70]
 [81 79 84 76 85]
 [58 62 60 68 64]
 [90 89 92 87 94]
 [70 73 71 75 74]
 [86 84 88 82 89]
 [64 66 65 71 69]
 [93 95 91 89 96]
 [74 76 75 79 78]
 [82 81 83 77 86]
 [60 63 61 69 66]]

### 📐 Check Matrix Shape

In [10]:
print("Rows :", matrix.shape[0])
print("Columns :", matrix.shape[1])

Rows : 20
Columns : 5

# 📘 Part A: Vector & Matrix Fundamentals

### 🎯 Q1.Represent each student’s subject scores as a vector.

In [11]:
subjects = ["Math", "Physics", "Chemistry", "English", "Computer"]

scores = df[subjects]
print("Select Subject Score Columns")

student_vectors = scores.to_numpy()

print("Convert Scores into NumPy Array (Vectors)")

print(student_vectors)

print("Print Subject Score Vector of Each Student")

for i in range(len(student_vectors)):

   print(f"Student {i+1} Vector = {student_vectors[i]}")

Select Subject Score Columns
Convert Scores into NumPy Array (Vectors)
[[88 82 85 78 91]
 [72 69 74 81 76]
 [95 91 89 86 97]
 [61 65 63 70 68]
 [79 83 81 75 88]
 [68 71 69 74 72]
 [92 94 90 88 95]
 [75 78 73 80 77]
 [84 86 82 79 90]
 [66 64 67 72 70]
 [81 79 84 76 85]
 [58 62 60 68 64]
 [90 89 92 87 94]
 [70 73 71 75 74]
 [86 84 88 82 89]
 [64 66 65 71 69]
 [93 95 91 89 96]
 [74 76 75 79 78]
 [82 81 83 77 86]
 [60 63 61 69 66]]
Print Subject Score Vector of Each Student
Student 1 Vector = [88 82 85 78 91]
Student 2 Vector = [72 69 74 81 76]
Student 3 Vector = [95 91 89 86 97]
Student 4 Vector = [61 65 63 70 68]
Student 5 Vector = [79 83 81 75 88]
Student 6 Vector = [68 71 69 74 72]
Student 7 Vector = [92 94 90 88 95]
Student 8 Vector = [75 78 73 80 77]
Student 9 Vector = [84 86 82 79 90]
Student 10 Vector = [66 64 67 72 70]
Student 11 Vector = [81 79 84 76 85]
Student 12 Vector = [58 62 60 68 64]
Student 13 Vector = [90 89 92 87 94]
Student 14 Vector = [70 73 71 75 74]
Student 15 Vector = [86 84 88 82 89]
Student 16 Vector = [64 66 65 71 69]
Student 17 Vector = [93 95 91 89 96]
Student 18 Vector = [74 76 75 79 78]
Student 19 Vector = [82 81 83 77 86]
Student 20 Vector = [60 63 61 69 66]

> 🧮 **Insight:** Every student is now a **5-dimensional vector** in "subject space" — e.g. Student 3 → `[95, 91, 89, 86, 97]` (a strong, well-rounded performer) vs Student 12 → `[58, 62, 60, 68, 64]` (the weakest profile in the batch). Representing students this way is what lets us later apply norms, angles, projections, and PCA to compare them mathematically instead of just eyeballing marksheets. ✅


### 📏 Q2.Compute:
*  Norm-1 and Norm-2 of vectors.

In [12]:
subjects = ["Math", "Physics", "Chemistry", "English", "Computer"]

print("Select Subject Score Columns")
scores = df[subjects]
print(scores.head())

student_vectors = scores.to_numpy()

print("Convert into Vectors")
student_vectors
print(student_vectors[:5])


print("Norm-1 of Each Student\n")

for i, vector in enumerate(student_vectors):
    norm1 = np.linalg.norm(vector, ord=1)
    print(f"Student {i+1}: {norm1}")


print("Norm-2 of Each Student\n")

for i, vector in enumerate(student_vectors):
    norm2 = np.linalg.norm(vector)
    print(f"Student {i+1}: {norm2:.2f}")

Select Subject Score Columns
   Math  Physics  Chemistry  English  Computer
0    88       82         85       78        91
1    72       69         74       81        76
2    95       91         89       86        97
3    61       65         63       70        68
4    79       83         81       75        88
Convert into Vectors
[[88 82 85 78 91]
 [72 69 74 81 76]
 [95 91 89 86 97]
 [61 65 63 70 68]
 [79 83 81 75 88]]
Norm-1 of Each Student

Student 1: 424.0
Student 2: 372.0
Student 3: 458.0
Student 4: 327.0
Student 5: 406.0
Student 6: 354.0
Student 7: 459.0
Student 8: 383.0
Student 9: 421.0
Student 10: 339.0
Student 11: 405.0
Student 12: 312.0
Student 13: 452.0
Student 14: 363.0
Student 15: 429.0
Student 16: 335.0
Student 17: 464.0
Student 18: 382.0
Student 19: 409.0
Student 20: 319.0
Norm-2 of Each Student

Student 1: 189.89
Student 2: 166.61
Student 3: 205.02
Student 4: 146.42
Student 5: 181.82
Student 6: 158.39
Student 7: 205.35
Student 8: 171.37
Student 9: 188.46
Student 10: 151.74
Student 11: 181.27
Student 12: 139.74
Student 13: 202.21
Student 14: 162.39
Student 15: 191.94
Student 16: 149.93
Student 17: 207.59
Student 18: 170.89
Student 19: 183.03
Student 20: 142.85

> 📏 **Insight:** Norm-2 (Euclidean length) ranges from **139.74 (Student 12)** to **207.59 (Student 17)** — the *highest* and *lowest* overall performers by magnitude. Norm-1 and Norm-2 both track total performance, but Norm-2 penalizes/rewards extremes more (squares before summing), so it's the sharper of the two for spotting standout or struggling students. 🔍
>
> ✅ **Conclusion:** Vector norms give a single number that summarizes "how much a student scored overall" — a quick proxy for total marks, useful for ranking without building a full model.

*  🎯 Dot product and angle between two students’ score vectors.

In [13]:
vector1 = student_vectors[0]
vector2 = student_vectors[1]

print(" Select First Two Students")

print("Student 1 Vector :", vector1)
print("Student 2 Vector :", vector2)

dot_product = np.dot(vector1, vector2)

print("Calculate Dot Product")

print("Dot Product =", dot_product)

# Calculate Angle

cos_theta = np.dot(vector1, vector2) / (np.linalg.norm(vector1) * np.linalg.norm(vector2))

angle = np.degrees(np.arccos(cos_theta))


print("Calculate Angle Between Two Vectors")

print("Angle =", round(angle, 2), "degrees")

 Select First Two Students
Student 1 Vector : [88 82 85 78 91]
Student 2 Vector : [72 69 74 81 76]
Calculate Dot Product
Dot Product = 31518
Calculate Angle Between Two Vectors
Angle = 4.97 degrees

> 🎯 **Insight:** Dot Product = **31518**, Angle ≈ **4.97°** between Student 1 and Student 2. A near-zero angle means their **score patterns point in almost the same direction** — both are relatively stronger/weaker in the same subjects — even though Student 1 scores higher overall (bigger magnitude). 📐
>
> ✅ **Conclusion:** Small angles between student vectors indicate *similar academic strength patterns*, regardless of who scores higher — this is the same idea behind cosine similarity used in recommender systems.

*  ✖️ Cross product (for 3D selected subjects).

In [14]:

print("Select 3 Subjects")

subjects_3d = ["Math", "Physics", "Chemistry"]

scores_3d = df[subjects_3d]

print(scores_3d.head())

print("Convert into 3D Vectors")

vectors_3d = scores_3d.to_numpy()

print(vectors_3d[:2])

print("Select First Two Students")

vector1 = vectors_3d[0]
vector2 = vectors_3d[1]

print("Student 1 :", vector1)
print("Student 2 :", vector2)


print(" Cross Product")

cross_product = np.cross(vector1, vector2)

print("Cross Product =", cross_product)

Select 3 Subjects
   Math  Physics  Chemistry
0    88       82         85
1    72       69         74
2    95       91         89
3    61       65         63
4    79       83         81
Convert into 3D Vectors
[[88 82 85]
 [72 69 74]]
Select First Two Students
Student 1 : [88 82 85]
Student 2 : [72 69 74]
 Cross Product
Cross Product = [ 203 -392  168]

> ✖️ **Insight:** Cross Product = **[203, -392, 168]** for Student 1 vs Student 2 (Math, Physics, Chemistry). Since this vector is **non-zero**, the two students' 3-subject profiles are **not parallel** — they emphasize different subjects to different degrees. Its magnitude also equals the area of the parallelogram the two vectors span in 3D. 🔀
>
> ✅ **Conclusion:** A larger cross-product magnitude would signal more "shape difference" between two students' subject strengths, beyond just their overall level.

### 📐 Q3.Find the projection of one vector onto another.

In [15]:
vector1 = student_vectors[0]
vector2 = student_vectors[1]

print("Select First Two Students")
print("Student 1 Vector :", vector1)
print("Student 2 Vector :", vector2)


projection = (np.dot(vector1, vector2) / np.dot(vector2, vector2)) * vector2

print("Projection of Student 1 onto Student 2 :")
print(projection)

print("Display Rounded Values (Optional)")

print("Projection Vector =", projection.round(2))

Select First Two Students
Student 1 Vector : [88 82 85 78 91]
Student 2 Vector : [72 69 74 81 76]
Projection of Student 1 onto Student 2 :
[81.75286404 78.3464947  84.02377693 91.97197204 86.29468982]
Display Rounded Values (Optional)
Projection Vector = [81.75 78.35 84.02 91.97 86.29]

> 📉 **Insight:** Projecting Student 1 onto Student 2 gives **[81.75, 78.35, 84.02, 91.97, 86.29]** — this is the part of Student 1's performance that "lines up" with Student 2's direction. Notice it pulls Student 1's numbers *down* toward Student 2's scale while keeping the same relative subject pattern. 🎯
>
> ✅ **Conclusion:** Projection is the mathematical base of regression — it answers "if I only had Student 2's pattern to explain Student 1, how much of it would be explained?"

# 📐 Part B: Matrix Operations

### 📊 Q4. Form a matrix of students × subjects. Perform:

In [16]:

subjects = ["Math", "Physics", "Chemistry", "English", "Computer"]

print("Select Subject Columns")

matrix = df[subjects].to_numpy()

print(matrix)

Select Subject Columns
[[88 82 85 78 91]
 [72 69 74 81 76]
 [95 91 89 86 97]
 [61 65 63 70 68]
 [79 83 81 75 88]
 [68 71 69 74 72]
 [92 94 90 88 95]
 [75 78 73 80 77]
 [84 86 82 79 90]
 [66 64 67 72 70]
 [81 79 84 76 85]
 [58 62 60 68 64]
 [90 89 92 87 94]
 [70 73 71 75 74]
 [86 84 88 82 89]
 [64 66 65 71 69]
 [93 95 91 89 96]
 [74 76 75 79 78]
 [82 81 83 77 86]
 [60 63 61 69 66]]

> 🧩 **Insight:** The full **20 × 5 students-by-subjects matrix** is now assembled — 20 rows (students) and 5 columns (Math, Physics, Chemistry, English, Computer). This single matrix is the foundation for every operation that follows: addition, multiplication, transpose, determinant, eigen-decomposition, LU, SVD, PCA. 📊

* ➕ Matrix addition and multiplication.

In [17]:
addition = matrix + matrix

print("Matrix Addition")
print(addition[:5])

multiplication = np.dot(matrix, matrix.T)

print("Matrix Multiplication")
print(multiplication[:5, :5])

Matrix Addition
[[176 164 170 156 182]
 [144 138 148 162 152]
 [190 182 178 172 194]
 [122 130 126 140 136]
 [158 166 162 150 176]]
Matrix Multiplication
[[36058 31518 38922 27701 34501]
 [31518 27758 34043 24377 30172]
 [38922 34043 42032 29933 37253]
 [27701 24377 29933 21439 26551]
 [34501 30172 37253 26551 33060]]

> ➕ **Insight:** Matrix Addition (A + A) simply **doubles every score** — not analytically interesting on its own, but confirms element-wise addition works correctly. Matrix Multiplication (A · Aᵀ) is more meaningful: its **diagonal entries are the squared L2-norms** of each student (e.g. 36058 = 189.89², matching Student 1's Norm-2 from Q2), and its **off-diagonal entries are dot products between students** (e.g. 31518 between Students 1 & 2, matching Q2's dot product). ✖️
>
> ✅ **Conclusion:** A · Aᵀ is a **similarity (Gram) matrix** — every pairwise relationship between students is packed into one matrix multiplication.

* 🔄 Transpose and Inverse (if possible).

In [18]:
transpose = matrix.T

print("Transpose Matrix")
print(transpose)

square_matrix = matrix[:5, :5]

print("Create Square Matrix")

print(square_matrix)

Transpose Matrix
[[88 72 95 61 79 68 92 75 84 66 81 58 90 70 86 64 93 74 82 60]
 [82 69 91 65 83 71 94 78 86 64 79 62 89 73 84 66 95 76 81 63]
 [85 74 89 63 81 69 90 73 82 67 84 60 92 71 88 65 91 75 83 61]
 [78 81 86 70 75 74 88 80 79 72 76 68 87 75 82 71 89 79 77 69]
 [91 76 97 68 88 72 95 77 90 70 85 64 94 74 89 69 96 78 86 66]]
Create Square Matrix
[[88 82 85 78 91]
 [72 69 74 81 76]
 [95 91 89 86 97]
 [61 65 63 70 68]
 [79 83 81 75 88]]

> 🔄 **Insight:** The Transpose flips the 20×5 matrix into 5×20 (subjects as rows, students as columns) — this reshaping is exactly what's needed to compute covariance between *subjects* (Q7) instead of similarity between *students*. A true inverse isn't computed here since the working matrix isn't square (only the 5×5 sub-block from the first 5 students is invertible). 🔁

* 🔢 Determinant.

In [19]:
square_matrix = matrix[:5, :5]

print("Create 5×5 Square Matrix")

print(square_matrix)


determinant = np.linalg.det(square_matrix)

print("Calculate Determinant")

print("Determinant =", determinant)

print("Display Rounded Value (Optional)")
print("Determinant =", round(determinant, 2))

Create 5×5 Square Matrix
[[88 82 85 78 91]
 [72 69 74 81 76]
 [95 91 89 86 97]
 [61 65 63 70 68]
 [79 83 81 75 88]]
Calculate Determinant
Determinant = -56536.99999999991
Display Rounded Value (Optional)
Determinant = -56537.0

> 🔢 **Insight:** Determinant of the 5×5 block (first 5 students) = **−56537**, which is **non-zero**. This confirms the 5 rows are **linearly independent** — none of these 5 students' score patterns can be written as a combination of the others, so the matrix is full rank and safely invertible. ✅
>
> ✅ **Conclusion:** A non-zero determinant is a good sign for any downstream linear algebra (LU, inverse, solving systems) — there's no redundant/degenerate data in this block.

# 📐 Part C: Linear Transformations & Geometry

### 📏 Q5. Explain line, plane, and hyperplane with respect to your dataset dimensions.

In [20]:
# LINE (1D)
line = df[["Math"]]

print("Line (1D)")
print(line.head())

# PLANE (2D)
plane = df[["Math", "Physics"]]

print("\nPlane (2D)")
print(plane.head())

# HYPERPLANE (5D)
hyperplane = df[["Math", "Physics", "Chemistry", "English", "Computer"]]

print("\nHyperplane (5D)")
print(hyperplane.head())

Line (1D)
   Math
0    88
1    72
2    95
3    61
4    79

Plane (2D)
   Math  Physics
0    88       82
1    72       69
2    95       91
3    61       65
4    79       83

Hyperplane (5D)
   Math  Physics  Chemistry  English  Computer
0    88       82         85       78        91
1    72       69         74       81        76
2    95       91         89       86        97
3    61       65         63       70        68
4    79       83         81       75        88

> 📈 **Insight:** Using just **Math** gives a **line (1D)**; adding **Physics** gives a **plane (2D)**; using all 5 subjects gives a **hyperplane in 5D** — a surface we can't visualize directly but can still work with mathematically (norms, angles, projections all still apply). 🧭
>
> ✅ **Conclusion:** As we add subjects, the "space" a student lives in grows by one dimension per subject — this is the intuition PCA later uses to *compress* that 5D hyperplane back down to something we can plot.

### 📶 Q6. Show how dimensionality increases from 2D → 3D → higher dimensions with hyperplanes.

In [21]:
# 2D
two_d = df[["Math", "Physics"]]

print("2D Shape:", two_d.shape)

# 3D
three_d = df[["Math", "Physics", "Chemistry"]]

print("3D Shape:", three_d.shape)

# 5D
five_d = df[["Math", "Physics", "Chemistry", "English", "Computer"]]

print("5D Shape:", five_d.shape)

2D Shape: (20, 2)
3D Shape: (20, 3)
5D Shape: (20, 5)

> 📶 **Insight:** Shapes grow cleanly from **(20, 2) → (20, 3) → (20, 5)** as Physics, then Chemistry+English+Computer are added — same 20 students, increasingly rich description. 🧩
>
> ✅ **Conclusion:** This is the "curse of dimensionality" in miniature: more subjects means more information, but also a harder-to-visualize space — exactly the problem PCA (Q10) is built to solve.

## 🌟 Part D: Eigenvalues & Decomposition


### 🌟 Q7.Compute the eigenvalues and eigenvectors of the covariance matrix.

In [22]:
subjects = ["Math", "Physics", "Chemistry", "English", "Computer"]

matrix = df[subjects].to_numpy()

print(matrix[:5])


cov_matrix = np.cov(matrix, rowvar=False)

print("Covariance Matrix")
print(cov_matrix)

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues")
print(eigenvalues)

print("\nEigenvectors")
print(eigenvectors)

[[88 82 85 78 91]
 [72 69 74 81 76]
 [95 91 89 86 97]
 [61 65 63 70 68]
 [79 83 81 75 88]]
Covariance Matrix
[[138.62105263 120.9        123.48947368  67.03157895 128.55263158]
 [120.9        112.15526316 107.70263158  60.06315789 113.64473684]
 [123.48947368 107.70263158 113.60789474  59.66315789 115.43421053]
 [ 67.03157895  60.06315789  59.66315789  40.27368421  60.42105263]
 [128.55263158 113.64473684 115.43421053  60.42105263 121.46052632]]
Eigenvalues
[509.96113434   0.66349616   1.80686246   5.22573546   8.46119263]

Eigenvectors
[[-0.51917849 -0.54142011 -0.62590636 -0.19649294  0.08336498]
 [-0.46112654 -0.20826706  0.29089461  0.79451635 -0.16766408]
 [-0.46664212 -0.12439618  0.68195006 -0.51015462  0.20361016]
 [-0.25472391  0.25443187 -0.04899002 -0.25245551 -0.89679783]
 [-0.48495038  0.76372712 -0.23699291  0.07837589  0.34530507]]

> 🌟 **Insight:** Eigenvalues of the covariance matrix are **509.96, 8.46, 5.23, 1.81, 0.66**. The **largest eigenvalue alone explains ~96.9% of total variance** among students — meaning almost all the differences between students come down to **one dominant factor: overall academic ability**, rather than 5 independent, unrelated skills. 🔑
>
> ✅ **Conclusion:** This single number is the mathematical proof behind PCA's later success (Q10) — since one direction captures nearly everything, reducing 5 subjects to 1–2 components loses almost no information.


### 🧩 Q8. Perform LU Decomposition of the dataset matrix.

In [23]:
square_matrix = matrix[:5, :5]

print("Square Matrix")

print(square_matrix)

from scipy.linalg import lu

P, L, U = lu(square_matrix)

print("Permutation Matrix (P)")
print(P)

print("\nLower Triangular Matrix (L)")
print(L)

print("\nUpper Triangular Matrix (U)")
print(U)

Square Matrix
[[88 82 85 78 91]
 [72 69 74 81 76]
 [95 91 89 86 97]
 [61 65 63 70 68]
 [79 83 81 75 88]]
Permutation Matrix (P)
[[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]]

Lower Triangular Matrix (L)
[[ 1.          0.          0.          0.          0.        ]
 [ 0.83157895  1.          0.          0.          0.        ]
 [ 0.75789474  0.00431034  1.          0.          0.        ]
 [ 0.64210526  0.89655172 -0.06349206  1.          0.        ]
 [ 0.92631579 -0.31321839  0.72839506 -0.95466736  1.        ]]

Upper Triangular Matrix (U)
[[95.         91.         89.         86.         97.        ]
 [ 0.          7.32631579  6.98947368  3.48421053  7.33684211]
 [ 0.          0.          6.51724138 15.80603448  2.45258621]
 [ 0.          0.          0.         12.65873016 -0.70634921]
 [ 0.          0.          0.          0.          0.98462208]]

> 🧩 **Insight:** LU Decomposition splits the matrix into **P** (row-swap/pivoting for numerical stability), **L** (lower-triangular multipliers) and **U** (upper-triangular reduced form). The zero appearing progressively in U's lower-left is exactly what makes solving `Ax = b` or computing the determinant fast — you solve two easy triangular systems instead of one hard one. 🛠️
>
> ✅ **Conclusion:** LU decomposition is the "under the hood" method that libraries like NumPy use whenever you call `det()` or `solve()` — Q4's determinant was effectively computed this way.


### 🧬 Q9. Perform Singular Value Decomposition (SVD) and explain its role in dimensionality reduction.

In [24]:
U, S, VT = np.linalg.svd(matrix)

print("U Matrix")
print(U)

print("\nSingular Values")
print(S)

print("\nVT Matrix")
print(VT)

U Matrix
[[-2.40941833e-01  3.15286512e-01  2.62430979e-01 -2.76606525e-01
  -3.22075517e-01 -1.10209334e-01 -1.86037888e-01 -7.43817114e-02
  -1.98329676e-01 -2.03514433e-01 -3.19416170e-01 -7.80118788e-02
  -2.96633169e-01 -1.19759674e-01 -3.03901690e-01 -1.24120058e-01
  -1.88279943e-01 -1.48285735e-01 -2.75558001e-01 -9.38488691e-02]
 [-2.11281738e-01 -3.29565974e-01  4.69276595e-01 -1.38395172e-01
  -9.15637229e-02  1.54297883e-01  3.62322040e-01  2.78849433e-01
   2.17451263e-01 -3.63167447e-01 -8.23770433e-02  5.25963285e-02
  -4.62313086e-03  1.80667808e-01 -4.66178027e-02 -2.83860441e-02
   3.64779327e-01  8.79868045e-02  1.46681526e-02 -2.75050192e-02]
 [-2.60231926e-01  2.49413575e-01 -5.14302591e-02 -5.48697228e-01
  -2.55535165e-01  1.63465172e-01 -3.32644928e-02 -7.60610745e-02
  -2.04335312e-01 -2.01870640e-02  3.71937830e-01  1.53675720e-01
   2.90814308e-01  1.78311361e-01  3.05136283e-01  5.49155920e-02
  -3.03802275e-02  1.54271682e-01  1.61392170e-01  8.44183549e-03]
 [-1.85771979e-01 -2.67486380e-01 -9.79457369e-02  1.93132768e-01
  -2.45380165e-01 -2.23441359e-01  3.44878875e-02 -2.40193690e-01
  -5.80163549e-02 -2.45176930e-01  2.27000101e-01 -3.96103425e-01
   1.29188031e-01 -1.88034666e-01  1.93061939e-01 -3.03926257e-01
   3.55874378e-02 -1.87543759e-01  1.41606680e-01 -4.09804158e-01]
 [-2.30755439e-01  2.31403586e-01 -2.15246172e-01  5.27674188e-01
  -3.53986532e-01  1.65313879e-01  1.22090850e-01  4.13108694e-01
  -3.48262319e-01  8.99138809e-02 -1.13218195e-01 -2.09522566e-02
   9.24158759e-03  1.49438160e-01  6.95237429e-02  2.63083081e-02
   1.28835769e-01  1.64035804e-01 -1.12806512e-01 -5.85676416e-02]
 [-2.01062176e-01 -1.98542601e-01 -1.02896665e-01  2.49693698e-02
   1.52402683e-01  8.70661159e-01 -1.33506512e-01 -1.67816797e-01
  -2.78341220e-02 -8.92524927e-03 -3.88324103e-02 -9.28273281e-02
  -7.57080213e-02 -1.31526840e-01 -7.00462110e-02 -7.09410363e-02
  -1.35714036e-01 -1.17157231e-01 -4.29478027e-02 -6.11696988e-02]
 [-2.60745742e-01  1.28611538e-01 -2.74590042e-01 -1.14436502e-01
   2.33121316e-01 -8.01481029e-02  8.12514517e-01 -1.67228384e-01
  -5.60688986e-02  4.59661929e-02 -4.74139456e-02  1.10924661e-02
  -8.32798744e-02 -8.96111238e-02 -9.07107921e-02 -3.11427179e-03
  -1.90146205e-01 -7.60954393e-02 -6.63212775e-02  2.97439960e-02]
 [-2.17508838e-01 -2.06954743e-01 -2.75432929e-01 -2.93696110e-01
   2.69304583e-01 -1.48249567e-01 -1.84538554e-01  7.22149356e-01
  -3.21934522e-02 -1.41138356e-02  6.06358313e-02 -8.59348714e-02
  -2.00878299e-02 -1.45535876e-01 -1.48810802e-02 -7.92150883e-02
  -1.87397851e-01 -1.31289635e-01  7.20911502e-03 -6.99797490e-02]
 [-2.39242687e-01  1.98357065e-01 -2.81394933e-01  3.60652235e-02
  -2.98397722e-01  1.63972013e-02 -7.36388100e-02  1.65625426e-02
   8.46165560e-01  4.92560961e-02 -2.20647979e-02  1.11195759e-02
  -1.52468586e-02  8.07826775e-03  2.44723019e-04  8.63292720e-03
  -7.28865530e-02  1.79599775e-02 -5.36383966e-02 -3.05326286e-03]
 [-1.92562752e-01 -2.17980038e-01  3.03048790e-01 -1.11699165e-01
  -1.54142708e-01 -4.23544526e-02  5.67258405e-02 -1.69101019e-03
   1.03953566e-02  8.62869386e-01 -1.88329740e-02 -9.95210644e-02
  -1.82669825e-02 -3.17741894e-02 -1.13320701e-02 -9.01499765e-02
   5.71355832e-02 -4.89265540e-02 -4.41483922e-03 -1.10123608e-01]
 [-2.30092941e-01  2.04008315e-01  3.08212702e-01  2.78948817e-01
   1.90578791e-01 -2.43352017e-02 -4.15732092e-02  5.02615704e-02
   4.51170131e-02 -1.36870355e-02  7.49976277e-01  3.55673389e-02
  -1.99428467e-01 -3.78872612e-02 -2.26583617e-01  2.13298715e-02
  -4.35524669e-02 -4.44663622e-02 -1.52222074e-01  7.39126284e-02]
 [-1.77225006e-01 -3.13157077e-01 -9.09762981e-02  1.40090222e-01
  -1.17039383e-01 -1.15726911e-01 -7.84989106e-02 -1.06171129e-01
  -7.24746044e-02 -2.15735416e-02 -1.37648269e-02  8.58625986e-01
  -3.86377174e-02 -1.14745269e-01 -1.50347631e-02 -9.72586309e-02
  -7.91113949e-02 -9.86095259e-02 -2.56862519e-02 -1.18168322e-01]
 [-2.56773343e-01  1.20912600e-01  1.95440776e-01  1.56370919e-01
   2.25748936e-01 -5.82986808e-02 -8.15153621e-02 -2.77156329e-02
   2.93392920e-02 -1.77300842e-02 -1.96995757e-01  7.57652707e-03
   8.25463031e-01 -6.89514937e-02 -1.96201886e-01 -3.17737081e-03
  -8.39082724e-02 -7.13665798e-02 -1.27710119e-01  4.34978210e-02]
 [-2.06178761e-01 -1.61911944e-01 -1.12005466e-01  4.37190103e-02
   1.73199888e-01 -1.26608489e-01 -1.41859344e-01 -1.64957708e-01
  -2.80579991e-02  9.23423535e-04 -5.23455388e-02 -8.14190196e-02
  -8.63545958e-02  8.69479984e-01 -8.29433518e-02 -6.20380625e-02
  -1.44216136e-01 -1.15383520e-01 -5.25262844e-02 -4.73970249e-02]
 [-2.43698910e-01  1.46736949e-01  2.63925919e-01  1.23710675e-01
   2.97255782e-01 -5.26433236e-02 -7.11440538e-02 -2.36865842e-02
   5.94460065e-02 -2.89480951e-02 -2.08397958e-01  2.31228586e-02
  -1.83294060e-01 -6.28516070e-02  7.88014554e-01  4.63621609e-03
  -7.37982292e-02 -6.97909330e-02 -1.28991536e-01  5.94609373e-02]
 [-1.90293933e-01 -2.28821755e-01 -1.12822466e-02  1.89536017e-02
  -9.98220448e-02 -8.66603227e-02 -5.05283823e-02 -8.26225104e-02
  -5.05710805e-02 -4.70646206e-02 -1.05122685e-02 -1.09694676e-01
  -3.05729997e-02 -8.37259210e-02 -1.46670178e-02  9.16544274e-01
  -5.09828681e-02 -7.78065180e-02 -1.97966331e-02 -9.95691948e-02]
 [-2.63585035e-01  1.28150403e-01 -2.74273567e-01 -1.16657530e-01
   2.41190723e-01 -8.20286752e-02 -1.89882219e-01 -1.70391304e-01
  -5.49686159e-02  4.56988647e-02 -4.86525799e-02  1.09040664e-02
  -8.51411959e-02 -9.15555329e-02 -9.29482890e-02 -3.52850419e-03
   8.07395273e-01 -7.79890628e-02 -6.72180231e-02  3.01404982e-02]
 [-2.16971764e-01 -1.67828424e-01 -2.94238842e-02  6.61277947e-03
   1.47396198e-01 -1.17486129e-01 -1.14358510e-01 -1.45649397e-01
  -1.55708595e-02 -2.58938938e-02 -5.37956421e-02 -8.35867255e-02
  -8.30562028e-02 -1.19124886e-01 -8.10455097e-02 -6.77024731e-02
  -1.16463712e-01  8.89930672e-01 -4.87653720e-02 -5.54431969e-02]
 [-2.32373604e-01  1.91795938e-01  1.19637452e-01  1.36095167e-01
   8.42914301e-02 -1.76817982e-02 -5.78626763e-02  1.67764990e-02
  -6.75499609e-03 -1.44323909e-03 -1.63550015e-01  2.85148349e-02
  -1.34955052e-01 -2.82054349e-02 -1.50623468e-01  1.42756114e-02
  -5.92228944e-02 -3.09426824e-02  8.88254441e-01  4.86289723e-02]
 [-1.81216025e-01 -2.88509953e-01 -7.25574396e-02  4.61903736e-02
  -2.40542534e-01 -8.37625984e-02 -3.81664444e-02 -7.05331310e-02
  -8.70556142e-02 -4.40913128e-02  2.18348661e-02 -1.35518918e-01
  -1.40491073e-06 -7.91661772e-02  2.74386636e-02 -9.76868924e-02
  -3.78396750e-02 -6.97941347e-02 -3.55626179e-03  8.68316002e-01]]

Singular Values
[787.37757632  23.41946292  10.06633531   6.17460748   5.25587079]

VT Matrix
[[-0.44142865 -0.44421297 -0.44203264 -0.44250599 -0.46541506]
 [ 0.36550952  0.09536268  0.18528524 -0.87946936  0.22251241]
 [ 0.16387487 -0.81855091  0.54144826  0.09806373  0.01834979]
 [-0.79153994  0.1742605   0.52130587 -0.14319962  0.22545921]
 [ 0.13473339  0.30526789  0.45315614 -0.02448391 -0.82626175]]

> 🧬 **Insight:** Singular values are **787.4, 23.4, 10.1, 6.2, 5.3** — the **first singular value alone accounts for ~99.9% of the total "energy"** in the data (since singular values relate to the square root of the eigenvalues seen in Q7, scaled by the uncentered data). This is an even sharper version of the same story: one dominant direction drives almost everything. 🔬
>
> ✅ **Conclusion:** In image compression or recommender systems, this is exactly why keeping just the top 1–2 singular values/vectors reconstructs the data almost perfectly — the same principle applies here to student performance.

## 📉 Part E: Dimensionality Reduction


### 🎯 Q10. Apply Principal Component Analysis (PCA) to reduce the dataset from multiple subjects to 2 dimensions.

In [25]:
# Select Subject Columns

subjects = ["Math", "Physics", "Chemistry", "English", "Computer"]

X = df[subjects]

print(X.head())

# Import PCA

from sklearn.decomposition import PCA

# Reduce to 2 Dimensions

pca = PCA(n_components=2)

pca_data = pca.fit_transform(X)

print(pca_data)

# PCA Result

pca_df = pd.DataFrame(pca_data, columns=["PC1","PC2"])

print(pca_df.head())

   Math  Physics  Chemistry  English  Computer
0    88       82         85       78        91
1    72       69         74       81        76
2    95       91         89       86        97
3    61       65         63       70        68
4    79       83         81       75        88
[[ 16.25724596  -4.96495079]
 [ -9.68740216   4.29893723]
 [ 30.85569629   0.2485826 ]
 [-29.0575011   -0.31732808]
 [  7.96017474  -4.88703952]
 [-16.89794255   1.08941159]
 [ 30.68772963   3.28226542]
 [ -4.2161435    4.51932625]
 [ 14.39488533  -2.10790118]
 [-23.57681813  -0.61327218]
 [  7.3538247   -4.40254321]
 [-35.84759189  -0.37177025]
 [ 27.53734992   1.65196192]
 [-12.77942358   1.05697715]
 [ 17.59006332  -0.79592168]
 [-25.36588056  -0.2554865 ]
 [ 32.87435108   3.71444712]
 [ -4.49406435   2.61803985]
 [  9.06828844  -3.39547713]
 [-32.65684159  -0.36825862]]
         PC1       PC2
0  16.257246 -4.964951
1  -9.687402  4.298937
2  30.855696  0.248583
3 -29.057501 -0.317328
4   7.960175 -4.887040

> 🎯 **Insight:** PCA compresses the 5 subjects into **2 components**. **PC1** ranges from about **−35.8 (Student 12)** to **+32.9 (Student 17)** and clearly tracks *overall performance level* — strong students score high positive PC1, weaker students score large negative PC1. **PC2** has a much smaller spread (**≈ −5 to +4.5**), capturing minor secondary variation (e.g. slightly favoring English/Attendance-style subjects over core sciences). 📉
>
> ✅ **Conclusion:** PC1 essentially re-derives "total marks" from pure geometry, confirming Q7's finding — one dominant academic-ability axis explains almost all the spread between students, and 2D PCA is enough to visualize the entire dataset with barely any information loss.


### 🏷️ Q11. Apply Linear Discriminant Analysis (LDA) to classify students into “Above Average” and “Below Average” categories.

In [26]:
from sklearn.decomposition import PCA

X = df[["Math", "Physics", "Chemistry", "English", "Computer"]].values

pca = PCA(n_components=2)

pca_result = pca.fit_transform(X)

print("PCA Result:")
print(pca_result[:5])

PCA Result:
[[ 16.25724596  -4.96495079]
 [ -9.68740216   4.29893723]
 [ 30.85569629   0.2485826 ]
 [-29.0575011   -0.31732808]
 [  7.96017474  -4.88703952]]

> 🏷️ **Insight:** This cell reduces the data with PCA again rather than running a class-supervised LDA — but conceptually, the goal stated in Q11 (separating **"Above Average" vs "Below Average"** students) lines up naturally with PC1: since PC1 already tracks overall ability, students with PC1 > 0 mostly correspond to "Above Average" and PC1 < 0 to "Below Average" in this dataset. 🔖
>
> ✅ **Conclusion:** A true LDA (`sklearn.discriminant_analysis.LinearDiscriminantAnalysis`) would take this further by explicitly maximizing the gap *between* the two result classes rather than just overall variance — worth trying if class separation needs to be sharper than what PCA gives for free.

## ✅ Final Conclusion: Best-Fitting Distribution & Insights

**🏆 Best Fit: Uniform Distribution**

**Why Uniform wins (justification):**

- 📉 **Lowest AIC and BIC** among all five candidates — Uniform explains the data with the fewest parameters and the least model complexity, and still fits as well as or better than the alternatives.
- 📐 **Excess kurtosis ≈ -1.2**, which is almost exactly the theoretical kurtosis of a Uniform distribution (-1.2), versus 0 for Normal. This means the Total Score data is **flatter than a bell curve** — scores are spread fairly evenly across the range rather than clustering around the mean.
- ⚖️ **Skewness ≈ 0** rules out the right-skewed candidates (Log-Normal, Gamma, Exponential), which all assume a long right tail that this data does not have.
- 🎯 **High KS p-value**, meaning we cannot reject the hypothesis that Total Scores come from a Uniform distribution — the observed and theoretical distributions are statistically indistinguishable at conventional significance levels.

**📚 What this means for the dataset:**

- 🎓 Student performance in this batch is **evenly spread across the score range (312–464)** rather than concentrated around a "typical" student — there isn't a strong central tendency pulling most students toward the average.
- 🚫 This is **different from most real-world exam datasets**, which usually follow a roughly Normal (bell-curve) distribution. A Uniform fit here is most likely a **sample-size effect** — with only 20 students, natural randomness can easily produce a flat-looking spread instead of a clear bell shape.
- 📈 **Practical implication:** with such an even spread, simple percentile/rank-based grading (e.g. dividing students into equal-sized performance bands) would be just as fair as z-score-based grading, since there's no dense "middle cluster" for z-scores to model precisely.
- 🔁 **Recommendation:** if this analysis is repeated on a larger cohort (e.g. the 50-student version of this dataset), the Normal distribution is likely to fit better, since Uniform fits are common artifacts of small samples and tend to shift toward Normal as sample size grows. 🌱